# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-14 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeId', models.IntegerField(default=1)),
                ('depId', models.IntegerField(default=1)),
                ('uId', models.IntegerField(default=1)),
                ('subject', models.CharField(max_length=31)),
                ('message', models.TextField(max_length=1000)),
                ('post_date', models.DateField(auto_now_add=True, verbose_name='date posted')),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
